### ISSUE TITLE
UDP Buffer Size Warnings

### ISSUE THREAD

**Issue by razed11** [igorauad/docker-gnuradio-oot-dev#1]
When trying to run `dvbs2-rx` from the Docker container on an M1 Mac I'm getting warnings:

```
[WARNING] [UDP] The recv buffer could not be resized sufficiently.
Target sock buff size: 2500000 bytes.
Actual sock buff size: 212992 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.rmem_max=2500000
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2500000 bytes.
Actual sock buff size: 212992 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2500000
```

But these commands do not work in the container. I tried setting related values on MacOS but this had no effect:

```
$ sysctl -a | grep maxsockbuf                   
kern.ipc.maxsockbuf: 52500000
$ sysctl -a | grep nmb       
kern.ipc.nmbclusters: 411648
$ sudo sysctl -w net.inet.udp.recvspace=25000000
net.inet.udp.recvspace: 786896 -> 25000000
$ sudo sysctl -w net.inet.tcp.recvspace=25000000
net.inet.tcp.recvspace: 131072 -> 25000000
$ sudo sysctl -w net.inet.tcp.sendspace=25000000
net.inet.tcp.sendspace: 131072 -> 25000000
```

@igorauad Did you encounter these within your M1 environment?

**Comment by igorauad** [comment]
Hi @razed11 ,

Indeed, `sysctl` commands won't work inside a Docker container. This limitation is not specific to the M1, but rather to Docker on Mac in general. I'm not sure if there is a good solution these days. However, I think you might be able to work around it by adding the settings directly to `/etc/sysctl.conf` inside the container. You can run the following inside the container:

```
echo net.core.rmem_max=2500000 >> /etc/sysctl.conf
echo net.core.wmem_max=2500000 >> /etc/sysctl.conf 
``` 

See if that helps.

Btw, I run GR inside Docker most of the time. However, I have never used a USRP with Docker on Mac. I use an M1 for local development but use a USRP remotely on Linux. There I control the USRP with Docker on Linux. When Docker is running on a Linux host, the `sysctl` commands work provided the capability is granted to the container (e.g., with `--privileged`).

In any case, if the above suggestion works, just remember to launch the container with `--network=host` so that you can access the USRP. Also, you might find this alias handy for running GUI apps inside the container (see more info on [Docker hub](https://hub.docker.com/r/igorfreire/gnuradio-oot-dev#multiple-gnu-radio-versions-in-parallel)):

```
alias docker-gui='docker run --env="DISPLAY" -v $HOME/.Xauthority:/root/.Xauthority --network=host'
```

**Comment by razed11** [comment]
Thanks @igorauad. Yes I read through your documentation and set up a similar alias / shell function.

I have a Linux box. I'm going to build `dvbs2-rx` for that and use it, as you do, to talk to the USRP. I'll use the M1 docker container for running GNU Radio Companion which is a nice option.
